# Generated by Django 6.0.6 on 2026-09-03 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSAEquityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('mayfresh_account_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please check the account number. It should be exactly 10 digits.', regex='^\\d{10}$')])),
                ('customer_address', models.CharField(max_length=500)),
                ('rsa_pin', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Kindly ensure the PIN starts with 'PEN' followed by 12 digits.", regex='^PEN\\d{12}$')])),
                ('rsa_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('equity_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_eligible', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
