# Generated by Django 6.0.6 on 2026-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsaequityrequest',
            name='loan_facility_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='management_processing_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='monthly_repayment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='property_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='property_offer_letter_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='second_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rsaequityrequest',
            name='statement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
